services:
#    pierre_boissinot_sheet_translation.example:
#        class: PierreBoissinot\SheetTranslationBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  pierre_boissinot_sheet_translation.sheet:
    class: Translation\PlatformAdapter\Sheet\Sheet
    arguments: ["google_client", "plain_value"]
